on:
  pull_request:
    branches:
      - master
    paths:
      - "blog/*.md"
      - "blog/*.mdx"
      - "i18n/*/docusaurus-plugin-content-blog/*.md"
      - "i18n/*/docusaurus-plugin-content-blog/*.mdx"
      - ".github/workflows/markdownlint.yml"
      - ".github/.markdownlint.json"

jobs:
  cip-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .github/lintconfig.yml
          search_paths: |
            blog/*.md
            blog/*.mdx
            i18n/*/docusaurus-plugin-content-blog/*.md
            i18n/*/docusaurus-plugin-content-blog/*.mdx
